[NM-WS-2]: Create an initial filter conception(#2)
JJerome-NM/NM-WebSockets pull request #5
Opened 2023-08-13 15:26 UTC by JJerome-NM

2023-08-19 17:08 UTC, justme1135 requested changes

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/FilterComponent.java
> +    public Annotation[] getAnnotations() {
+1

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/FilterComponent.java
> +    public FilterComponent(Annotation[] annotations, WSFiltersComponent componentAnnotation,
+1

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/FilterComponent.java
> +    public WSFiltersComponent getComponentAnnotation() {
+1

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/FilterComponent.java
> +    public Class<?> getClazz() {
+1

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/FilterComponent.java
> +    public Object getSpringBean() {
+1

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/FiltersStorage.java
> +                .collect(Collectors.toMap(c -> c.getClass().getSimpleName(), c -> c));
use Function::identity

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/MappingFilterChain.java
> +    public String getLabel() {
use getters

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/MappingFilterChain.java
> +    public int getOrder() {
+1

2023-08-19 17:08 UTC, justme1135 commented on nm-websockets-filters/src/main/java/com/jjerome/MappingFilterProxy.java
> +    public WSMappingType getType() {
+1

2023-08-20 11:52 UTC, JJerome-NM commented on nm-websockets-common/src/main/java/com/jjerome/core/Request.java
> +    public Request() {
Yes, they could work here, but I stopped using "lombok" because I read that it is a bad practice in writing libraries

2023-08-20 11:58 UTC, JJerome-NM commented on nm-webosockets-test-application/src/main/java/com/jjerome_test/controller/TestWSController.java
> +    public void test(@WSRequestBody Good<Good<Good<Integer, Integer>, Integer>, Integer> good){
Yes, it looks confusing, but the purpose of this is to check whether a query with a large number of nested generics is correctly converted

2023-08-20 11:58 UTC, JJerome-NM commented on nm-webosockets-test-application/src/main/java/com/jjerome_test/controller/TestWSController.java
> +            responsePath = "ffg",
Renamed

2023-08-20 11:58 UTC, JJerome-NM commented on nm-webosockets-test-application/src/main/java/com/jjerome_test/controller/TestWSController.java
> +            path = "/2",
Renamed

2023-08-20 12:00 UTC, JJerome-NM commented on nm-websockets-common/src/main/java/com/jjerome/Main.java
> +        System.out.println("This is a library and cannot be run");
Yes, fixed

2023-08-22 06:17 UTC, justme1135 approved these changes

2023-08-22 10:24 UTC, merged